# Generated by Django 4.2.13 on 2024-07-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('m_pictures', models.ImageField(blank=True, null=True, upload_to='material_images/')),
                ('type_of_material', models.CharField(max_length=50)),
                ('factory', models.CharField(max_length=100)),
                ('geographical_origins', models.CharField(max_length=100)),
                ('physical_properties', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pigment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label_picture', models.CharField(max_length=100)),
                ('bottle_picture', models.CharField(max_length=100)),
                ('specific_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('shade', models.CharField(max_length=50)),
                ('stopper', models.CharField(max_length=50)),
                ('geographical_origins', models.CharField(max_length=100)),
                ('date_of_production', models.DateField()),
                ('chemical_composition', models.CharField(max_length=100)),
                ('physical_properties', models.CharField(max_length=100)),
                ('archive_description', models.TextField()),
            ],
        ),
    ]
