# Generated by Django 4.2.14 on 2024-07-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_material_pigment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigment',
            name='archive_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
