# Generated by Django 4.2.14 on 2024-07-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pigment_archive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigment',
            name='date_of_production',
            field=models.CharField(max_length=100),
        ),
    ]
