# Generated by Django 4.2.13 on 2024-07-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pigment_date_of_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='archive_id',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
