# Generated by Django 4.2.14 on 2024-07-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_pigment_label_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='m_pictures',
            field=models.ImageField(blank=True, default='static/IMGM/defaultmaterial.png', null=True, upload_to='static/IMGM/'),
        ),
        migrations.AlterField(
            model_name='pigment',
            name='bottle_picture',
            field=models.ImageField(default='static/IMGB/defaultbottle.png', upload_to='IMGB/'),
        ),
    ]
