# Generated by Django 4.2.13 on 2024-07-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_carouselitem_delete_item_delete_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(upload_to='Rectos/'),
        ),
    ]
