# Generated by Django 4.2.13 on 2024-07-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_carouselitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselitem',
            name='caption',
        ),
    ]
