# Generated by Django 4.2.13 on 2024-07-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_carouselitem_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
