# Generated by Django 4.2.14 on 2024-07-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_carouselitem_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('pagenumber', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/Rectos')),
                ('ms_number', models.CharField(max_length=50)),
                ('transcription', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CarouselItem',
        ),
    ]
