# Generated by Django 4.2.14 on 2024-07-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_transcription_delete_carouselitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transcription',
        ),
    ]
