# Generated by Django 4.2.14 on 2024-07-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_transcription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagenumber', models.TextField(max_length=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/Rectos')),
                ('ms_number', models.CharField(max_length=50)),
                ('transcription', models.TextField()),
            ],
        ),
    ]
