# Generated by Django 4.2.14 on 2024-07-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_transcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='pagenumber',
            field=models.TextField(max_length=50),
        ),
    ]
