# Generated by Django 4.2.14 on 2024-07-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_transcription_pagenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='m_pictures',
            field=models.ImageField(blank=True, default='main/static/IMGM/defaultmaterial.png', null=True, upload_to='main/static/IMGM/'),
        ),
        migrations.AlterField(
            model_name='pigment',
            name='bottle_picture',
            field=models.ImageField(default='main/static/IMGB/defaultbottle.png', upload_to='main/static/IMGB/'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/Rectos'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
